spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-cherry-665397.eu-central-1.aws.neon.tech/pucai
    username: lptrk
    password: H6OFSIXjipG7
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: /docs